### ISSUE TITLE
how to solve?

### ISSUE THREAD

**Issue by mister201433** [davidteren/lpx_links#31]
x README.md
x images/
x images/aria2_example.png
x install.sh
x lib/
x lib/file_helpers.rb
x lpx_links.rb
/Users/juanelcaballo/Downloads/lpx_links/app/lib/file_helpers.rb:24:in `app_path': Mainstage not found (RuntimeError)
	from /Users/juanelcaballo/Downloads/lpx_links/app/lib/file_helpers.rb:6:in `plist_file_path'
	from ./lpx_links.rb:50:in `convert_plist_to_json'
	from ./lpx_links.rb:33:in `run'
	from ./lpx_links.rb:97:in `<main>'
	
	
	I have MainStage 3.6.5

**Comment by davidteren** [comment]
Hi @mister201433, I have made some changes to the code. Please try again and let me know if you still encounter this issue.
Be sure to delete the `lpx_links` directory and run the command again.

`cd ~/Downloads; mkdir -p lpx_links/app ; cd lpx_links/app ; curl -#L https://goo.gl/nUrpPi | tar -xzv --strip-components 1 ; ./lpx_links.rb -n Mainstage`
